server:
  port: 28803

spring:
  datasource:
    url: jdbc:sqlite:D:/java/sqlite-tools-win-x64-3500300/goodsop_rk3562.db
    driver-class-name: org.sqlite.JDBC


# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# MQTT配置
mqtt:
  env: dev02
  device-model: A10
#  device-model: RK3562
  server-url: ssl://dev.goodsop.cn:8883
  connection-timeout: 30
  keep-alive-interval: 60
  automatic-reconnect: true
  clean-session: false
  heartbeat-interval: 5

## 日志配置
#logging:
#  level:
#    root: DEBUG
#    com.goodsop.devboard: DEBUG
#    org.springframework: DEBUG
#    org.springframework.boot: DEBUG
#    org.springframework.context: DEBUG
#    org.springframework.beans: DEBUG
#    com.baomidou.mybatisplus: DEBUG
#    org.eclipse.paho: WARN
#    org.hibernate: WARN